name: Deploy Voilà app to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install voila

      - name: Deploy with Voilà
        run: |
          pip install jupyterlab
          jupyter nbconvert --to html index.ipynb
          cp -r * $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          voila index.ipynb --no-browser --port=8000

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./voila
